import { Notification } from '@types';
export const mockNotifications: Notification[] = [
	{
		id: 9378,
		level: 'info',
		unread: true,
		actor_object_id: '9',
		verb: 'BOT [BackTesting] buy BTCUSDT',
		description: 'BOT *[BackTesting]* - *Buy* : 0.0015699 *BTCUSDT* - Buy price: 63697.56',
		target_object_id: null,
		action_object_object_id: null,
		timestamp: '1727044890',
		public: true,
		deleted: false,
		emailed: false,
		data: null,
		group: 'volbot',
		type: 3,
		verb_translate: null,
		desc_translate: null,
		key_verbose: 'title.bot.buy',
		key_descript: 'bot.spot.buy',
		format_value_verbose: {
			symbol: 'BTCUSDT',
			bot_name: 'BackTesting',
		},
		format_value_descript: {
			symbol: 'BTCUSDT',
			volume: 0.0015699,
			bot_name: 'BackTesting',
			bought_at: 63697.56,
		},
		recipient: 9,
		actor_content_type: 4,
		target_content_type: null,
		action_object_content_type: null,
		slug: 120287,
	},
	{
		id: 9379,
		level: 'info',
		unread: true,
		actor_object_id: '9',
		verb: 'BOT [BackTesting] buy BTCUSDT',
		description: 'BOT *[BackTesting]* - *Buy* : 0.0015699 *BTCUSDT* - Buy price: 63697.56',
		target_object_id: null,
		action_object_object_id: null,
		timestamp: '1727044890',
		public: true,
		deleted: false,
		emailed: false,
		data: null,
		group: 'volbot',
		type: 3,
		verb_translate: null,
		desc_translate: null,
		key_verbose: 'title.bot.buy',
		key_descript: 'bot.spot.buy',
		format_value_verbose: {
			symbol: 'BTCUSDT',
			bot_name: 'BackTesting',
		},
		format_value_descript: {
			symbol: 'BTCUSDT',
			volume: 0.0015699,
			bot_name: 'BackTesting',
			bought_at: 63697.56,
		},
		recipient: 9,
		actor_content_type: 4,
		target_content_type: null,
		action_object_content_type: null,
		slug: 120288,
	},
];
